"""initial schema

Revision ID: cadda1ab049a
Revises:
Create Date: 2026-08-13 13:37:26.719109

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cadda1ab049a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("system", "manual", name="task_created_by").create(op.get_bind())
    sa.Enum("open", "in_progress", "done", "overdue", name="task_status").create(op.get_bind())
    sa.Enum("sub_agent", "referral_client", "affiliate", name="partner_type").create(op.get_bind())
    sa.Enum("manual", "nps_parsed", name="accommodation_note_source").create(op.get_bind())
    sa.Enum("hotel", "sanatorium", name="accommodation_type").create(op.get_bind())
    sa.Enum("acquiring", "bank_transfer", "cash", "onec_sync", name="payment_method").create(
        op.get_bind()
    )
    sa.Enum("pending", "paid", "failed", "refunded", name="payment_status").create(op.get_bind())
    sa.Enum("in", "out", name="payment_direction").create(op.get_bind())
    sa.Enum("new", "processing", "converted", "duplicate", "spam", name="lead_status").create(
        op.get_bind()
    )
    sa.Enum("manual", "whatsapp", "telegram", "email", "ocr", name="attachment_source").create(
        op.get_bind()
    )
    sa.Enum("image", "document", "audio", "video", "other", name="attachment_file_type").create(
        op.get_bind()
    )
    sa.Enum("draft", "sent", "signed", name="document_status").create(op.get_bind())
    sa.Enum("contract", "invoice", "voucher", name="document_type").create(op.get_bind())
    sa.Enum(
        "accommodation", "flight", "transfer", "excursion", "other", name="deal_item_type"
    ).create(op.get_bind())
    sa.Enum("cruise", "tour", "sanatorium", name="funnel_type").create(op.get_bind())
    sa.Enum("in", "out", name="message_direction").create(op.get_bind())
    sa.Enum("whatsapp", "telegram", "email", "call", name="message_channel").create(op.get_bind())
    sa.Enum("phone", "email", "telegram", "whatsapp", "vk", name="client_contact_type").create(
        op.get_bind()
    )
    sa.Enum("create", "update", "delete", name="audit_action").create(op.get_bind())
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "white_label_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("slug", name=op.f("uq_companies_slug")),
    )
    op.create_table(
        "countries",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("code", name=op.f("uq_countries_code")),
        sa.UniqueConstraint("name", name=op.f("uq_countries_name")),
    )
    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("minor_unit", sa.Integer(), server_default="2", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "minor_unit >= 0 AND minor_unit <= 4", name=op.f("ck_currencies_minor_unit_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currencies")),
        sa.UniqueConstraint("code", name=op.f("uq_currencies_code")),
    )
    op.create_table(
        "cities",
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_cities_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("country_id", "name", name="uq_cities_country_id_name"),
    )
    op.create_index(op.f("ix_cities_country_id"), "cities", ["country_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("passport_series", sa.String(length=32), nullable=True),
        sa.Column("passport_number", sa.String(length=32), nullable=True),
        sa.Column("passport_issued_by", sa.String(length=255), nullable=True),
        sa.Column("passport_issued_date", sa.Date(), nullable=True),
        sa.Column("citizenship", sa.String(length=64), nullable=True),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column("health_data_consented_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=64)), server_default="{}", nullable=False
        ),
        sa.Column("source_lead_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_clients_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_lead_id"],
            ["leads.id"],
            name="fk_clients_source_lead",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(op.f("ix_clients_company_id"), "clients", ["company_id"], unique=False)
    op.create_table(
        "deal_stages",
        sa.Column(
            "funnel_type",
            postgresql.ENUM("cruise", "tour", "sanatorium", name="funnel_type", create_type=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("color_hex", sa.String(length=16), nullable=False),
        sa.Column("sla_hours", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "sla_hours IS NULL OR sla_hours > 0", name=op.f("ck_deal_stages_sla_hours_positive")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_deal_stages_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_stages")),
        sa.UniqueConstraint(
            "company_id",
            "funnel_type",
            "sort_order",
            deferrable=True,
            initially="DEFERRED",
            name="uq_deal_stages_company_id_funnel_type_sort_order",
        ),
    )
    op.create_index(op.f("ix_deal_stages_company_id"), "deal_stages", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_deal_stages_funnel_type"), "deal_stages", ["funnel_type"], unique=False
    )
    op.create_table(
        "leads",
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("raw_full_name", sa.String(length=255), nullable=True),
        sa.Column("raw_phone", sa.String(length=32), nullable=True),
        sa.Column("raw_email", sa.String(length=255), nullable=True),
        sa.Column("raw_message", sa.Text(), nullable=True),
        sa.Column(
            "form_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "new",
                "processing",
                "converted",
                "duplicate",
                "spam",
                name="lead_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("converted_client_id", sa.Uuid(), nullable=True),
        sa.Column("duplicate_of_lead_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leads_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["converted_client_id"],
            ["clients.id"],
            name="fk_leads_converted_client",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_lead_id"],
            ["leads.id"],
            name=op.f("fk_leads_duplicate_of_lead_id_leads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    op.create_index(op.f("ix_leads_company_id"), "leads", ["company_id"], unique=False)
    op.create_index(op.f("ix_leads_status"), "leads", ["status"], unique=False)
    op.create_table(
        "partners",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "sub_agent", "referral_client", "affiliate", name="partner_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("commission_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "commission_percent IS NULL OR (commission_percent >= 0 AND commission_percent <= 100)",
            name=op.f("ck_partners_commission_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_partners_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partners")),
    )
    op.create_index(op.f("ix_partners_company_id"), "partners", ["company_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_roles_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("company_id", "name", name="uq_roles_company_id_name"),
    )
    op.create_index(op.f("ix_roles_company_id"), "roles", ["company_id"], unique=False)
    op.create_table(
        "accommodations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("hotel", "sanatorium", name="accommodation_type", create_type=False),
            nullable=False,
        ),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_accommodations_city_id_cities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_accommodations_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_accommodations_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accommodations")),
    )
    op.create_index(op.f("ix_accommodations_city_id"), "accommodations", ["city_id"], unique=False)
    op.create_index(
        op.f("ix_accommodations_company_id"), "accommodations", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_accommodations_country_id"), "accommodations", ["country_id"], unique=False
    )
    op.create_table(
        "client_contacts",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "phone",
                "email",
                "telegram",
                "whatsapp",
                "vk",
                name="client_contact_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_readonly", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_contacts_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_client_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_contacts")),
        sa.UniqueConstraint("type", "value", name="uq_client_contacts_type_value"),
    )
    op.create_index(
        op.f("ix_client_contacts_client_id"), "client_contacts", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_contacts_company_id"), "client_contacts", ["company_id"], unique=False
    )
    op.create_index(
        "uq_client_contacts_primary",
        "client_contacts",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("max_active_deals", sa.Integer(), server_default="0", nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("last_login_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("password_changed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_users_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_company_id"), "users", ["company_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.create_table(
        "accommodation_notes",
        sa.Column("accommodation_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM(
                "manual", "nps_parsed", name="accommodation_note_source", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("fk_accommodation_notes_accommodation_id_accommodations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_accommodation_notes_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_accommodation_notes_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accommodation_notes")),
    )
    op.create_index(
        op.f("ix_accommodation_notes_accommodation_id"),
        "accommodation_notes",
        ["accommodation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accommodation_notes_company_id"),
        "accommodation_notes",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "accommodation_programs",
        sa.Column("accommodation_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("capacity", sa.Integer(), server_default="1", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "capacity > 0", name=op.f("ck_accommodation_programs_capacity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("fk_accommodation_programs_accommodation_id_accommodations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_accommodation_programs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accommodation_programs")),
    )
    op.create_index(
        op.f("ix_accommodation_programs_accommodation_id"),
        "accommodation_programs",
        ["accommodation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accommodation_programs_company_id"),
        "accommodation_programs",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "attachments",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column(
            "file_type",
            postgresql.ENUM(
                "image",
                "document",
                "audio",
                "video",
                "other",
                name="attachment_file_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            postgresql.ENUM(
                "manual",
                "whatsapp",
                "telegram",
                "email",
                "ocr",
                name="attachment_source",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_attachments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(op.f("ix_attachments_company_id"), "attachments", ["company_id"], unique=False)
    op.create_index(
        "ix_attachments_entity", "attachments", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "action",
            postgresql.ENUM("create", "update", "delete", name="audit_action", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "field_changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_audit_logs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_company_id"), "audit_logs", ["company_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "deals",
        sa.Column(
            "funnel_type",
            postgresql.ENUM("cruise", "tour", "sanatorium", name="funnel_type", create_type=False),
            nullable=False,
        ),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column("partner_id", sa.Uuid(), nullable=True),
        sa.Column("country_id", sa.Uuid(), nullable=True),
        sa.Column("city_id", sa.Uuid(), nullable=True),
        sa.Column("accommodation_id", sa.Uuid(), nullable=True),
        sa.Column("budget_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency_id", sa.Uuid(), nullable=True),
        sa.Column("date_from", sa.Date(), nullable=True),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column(
            "utm_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "date_from IS NULL OR date_to IS NULL OR date_from <= date_to",
            name=op.f("ck_deals_date_range_order"),
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("fk_deals_accommodation_id_accommodations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name=op.f("fk_deals_city_id_cities"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_deals_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_deals_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_deals_country_id_countries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_deals_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
            name=op.f("fk_deals_manager_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
            name=op.f("fk_deals_partner_id_partners"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["deal_stages.id"],
            name=op.f("fk_deals_stage_id_deal_stages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
    )
    op.create_index(op.f("ix_deals_client_id"), "deals", ["client_id"], unique=False)
    op.create_index(op.f("ix_deals_company_id"), "deals", ["company_id"], unique=False)
    op.create_index(op.f("ix_deals_funnel_type"), "deals", ["funnel_type"], unique=False)
    op.create_index(op.f("ix_deals_manager_id"), "deals", ["manager_id"], unique=False)
    op.create_index(op.f("ix_deals_partner_id"), "deals", ["partner_id"], unique=False)
    op.create_index(op.f("ix_deals_stage_id"), "deals", ["stage_id"], unique=False)
    op.create_table(
        "document_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "contract", "invoice", "voucher", name="document_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("accommodation_id", sa.Uuid(), nullable=True),
        sa.Column("template_body", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("fk_document_templates_accommodation_id_accommodations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_document_templates_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_templates")),
    )
    op.create_index(
        op.f("ix_document_templates_accommodation_id"),
        "document_templates",
        ["accommodation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_templates_company_id"), "document_templates", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_templates_type"), "document_templates", ["type"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("revoked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "call_logs",
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("phone_masked", sa.String(length=32), nullable=True),
        sa.Column("duration_sec", sa.Integer(), server_default="0", nullable=False),
        sa.Column("recording_url", sa.String(length=512), nullable=True),
        sa.Column("transcript_text", sa.Text(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_call_logs_client_id_clients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_call_logs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_call_logs_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_logs")),
    )
    op.create_index(op.f("ix_call_logs_company_id"), "call_logs", ["company_id"], unique=False)
    op.create_index(op.f("ix_call_logs_deal_id"), "call_logs", ["deal_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_comments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_comments_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_company_id"), "comments", ["company_id"], unique=False)
    op.create_index(op.f("ix_comments_deal_id"), "comments", ["deal_id"], unique=False)
    op.create_table(
        "deal_items",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "item_type",
            postgresql.ENUM(
                "accommodation",
                "flight",
                "transfer",
                "excursion",
                "other",
                name="deal_item_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("accommodation_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost_price_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("sale_price_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "cost_price_minor >= 0", name=op.f("ck_deal_items_cost_price_non_negative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_deal_items_quantity_positive")),
        sa.CheckConstraint(
            "sale_price_minor >= 0", name=op.f("ck_deal_items_sale_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("fk_deal_items_accommodation_id_accommodations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_deal_items_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_deal_items_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_deal_items_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_items")),
    )
    op.create_index(op.f("ix_deal_items_company_id"), "deal_items", ["company_id"], unique=False)
    op.create_index(op.f("ix_deal_items_deal_id"), "deal_items", ["deal_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "contract", "invoice", "voucher", name="document_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("draft", "sent", "signed", name="document_status", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_documents_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_documents_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["document_templates.id"],
            name=op.f("fk_documents_template_id_document_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_company_id"), "documents", ["company_id"], unique=False)
    op.create_index(op.f("ix_documents_deal_id"), "documents", ["deal_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column(
            "channel",
            postgresql.ENUM(
                "whatsapp", "telegram", "email", "call", name="message_channel", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("in", "out", name="message_direction", create_type=False),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("external_message_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_messages_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_messages_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_messages_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_client_id"), "messages", ["client_id"], unique=False)
    op.create_index(op.f("ix_messages_company_id"), "messages", ["company_id"], unique=False)
    op.create_index(op.f("ix_messages_deal_id"), "messages", ["deal_id"], unique=False)
    op.create_index(
        op.f("ix_messages_external_message_id"), "messages", ["external_message_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            postgresql.ENUM("in", "out", name="payment_direction", create_type=False),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending", "paid", "failed", "refunded", name="payment_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            postgresql.ENUM(
                "acquiring",
                "bank_transfer",
                "cash",
                "onec_sync",
                name="payment_method",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("external_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("paid_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_payments_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_payments_deal_id_deals"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_company_id"), "payments", ["company_id"], unique=False)
    op.create_index(op.f("ix_payments_deal_id"), "payments", ["deal_id"], unique=False)
    op.create_index(
        op.f("ix_payments_external_transaction_id"),
        "payments",
        ["external_transaction_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "tariff_entries",
        sa.Column("accommodation_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("season_start", sa.Date(), nullable=False),
        sa.Column("season_end", sa.Date(), nullable=False),
        sa.Column(
            "occupancy_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_tariff_entries_price_non_negative")),
        sa.CheckConstraint(
            "season_start <= season_end", name=op.f("ck_tariff_entries_season_order")
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("fk_tariff_entries_accommodation_id_accommodations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_tariff_entries_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_tariff_entries_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["accommodation_programs.id"],
            name=op.f("fk_tariff_entries_program_id_accommodation_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariff_entries")),
    )
    op.create_index(
        op.f("ix_tariff_entries_accommodation_id"),
        "tariff_entries",
        ["accommodation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tariff_entries_company_id"), "tariff_entries", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_tariff_entries_currency_id"), "tariff_entries", ["currency_id"], unique=False
    )
    op.create_index(
        op.f("ix_tariff_entries_program_id"), "tariff_entries", ["program_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open", "in_progress", "done", "overdue", name="task_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            postgresql.ENUM("system", "manual", name="task_created_by", create_type=False),
            nullable=False,
        ),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tasks_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_tasks_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_tasks_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_assignee_id"), "tasks", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_tasks_company_id"), "tasks", ["company_id"], unique=False)
    op.create_index(op.f("ix_tasks_deal_id"), "tasks", ["deal_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "tourists",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("is_lead_tourist", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("full_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("birth_date_snapshot", sa.Date(), nullable=True),
        sa.Column("passport_series", sa.String(length=32), nullable=True),
        sa.Column("passport_number", sa.String(length=32), nullable=True),
        sa.Column("passport_issued_by", sa.String(length=255), nullable=True),
        sa.Column("passport_issued_date", sa.Date(), nullable=True),
        sa.Column("citizenship_snapshot", sa.String(length=64), nullable=True),
        sa.Column(
            "snapshot_created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_tourists_client_id_clients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_tourists_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_tourists_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tourists")),
    )
    op.create_index(op.f("ix_tourists_company_id"), "tourists", ["company_id"], unique=False)
    op.create_index(op.f("ix_tourists_deal_id"), "tourists", ["deal_id"], unique=False)
    # ### end Alembic commands ###

    # Взаимные ссылки leads <-> clients: объявлены с use_alter, поэтому при
    # создании таблиц пропускаются (каждая ссылается на другую) и добавляются
    # отдельными командами после того, как обе таблицы существуют.
    op.create_foreign_key(
        "fk_clients_source_lead",
        "clients",
        "leads",
        ["source_lead_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_leads_converted_client",
        "leads",
        "clients",
        ["converted_client_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Взаимные ссылки снимаются первыми, иначе таблицы не удалить.
    op.drop_constraint("fk_leads_converted_client", "leads", type_="foreignkey")
    op.drop_constraint("fk_clients_source_lead", "clients", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tourists_deal_id"), table_name="tourists")
    op.drop_index(op.f("ix_tourists_company_id"), table_name="tourists")
    op.drop_table("tourists")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_deal_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_company_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assignee_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_tariff_entries_program_id"), table_name="tariff_entries")
    op.drop_index(op.f("ix_tariff_entries_currency_id"), table_name="tariff_entries")
    op.drop_index(op.f("ix_tariff_entries_company_id"), table_name="tariff_entries")
    op.drop_index(op.f("ix_tariff_entries_accommodation_id"), table_name="tariff_entries")
    op.drop_table("tariff_entries")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_transaction_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_deal_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_company_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_messages_external_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_deal_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_company_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_client_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_documents_deal_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_company_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_deal_items_deal_id"), table_name="deal_items")
    op.drop_index(op.f("ix_deal_items_company_id"), table_name="deal_items")
    op.drop_table("deal_items")
    op.drop_index(op.f("ix_comments_deal_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_company_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_call_logs_deal_id"), table_name="call_logs")
    op.drop_index(op.f("ix_call_logs_company_id"), table_name="call_logs")
    op.drop_table("call_logs")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_document_templates_type"), table_name="document_templates")
    op.drop_index(op.f("ix_document_templates_company_id"), table_name="document_templates")
    op.drop_index(op.f("ix_document_templates_accommodation_id"), table_name="document_templates")
    op.drop_table("document_templates")
    op.drop_index(op.f("ix_deals_stage_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_partner_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_manager_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_funnel_type"), table_name="deals")
    op.drop_index(op.f("ix_deals_company_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_client_id"), table_name="deals")
    op.drop_table("deals")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_company_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_attachments_entity", table_name="attachments")
    op.drop_index(op.f("ix_attachments_company_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_accommodation_programs_company_id"), table_name="accommodation_programs")
    op.drop_index(
        op.f("ix_accommodation_programs_accommodation_id"), table_name="accommodation_programs"
    )
    op.drop_table("accommodation_programs")
    op.drop_index(op.f("ix_accommodation_notes_company_id"), table_name="accommodation_notes")
    op.drop_index(op.f("ix_accommodation_notes_accommodation_id"), table_name="accommodation_notes")
    op.drop_table("accommodation_notes")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_company_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_client_contacts_primary",
        table_name="client_contacts",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index(op.f("ix_client_contacts_company_id"), table_name="client_contacts")
    op.drop_index(op.f("ix_client_contacts_client_id"), table_name="client_contacts")
    op.drop_table("client_contacts")
    op.drop_index(op.f("ix_accommodations_country_id"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_company_id"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_city_id"), table_name="accommodations")
    op.drop_table("accommodations")
    op.drop_index(op.f("ix_roles_company_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_partners_company_id"), table_name="partners")
    op.drop_table("partners")
    op.drop_index(op.f("ix_leads_status"), table_name="leads")
    op.drop_index(op.f("ix_leads_company_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_deal_stages_funnel_type"), table_name="deal_stages")
    op.drop_index(op.f("ix_deal_stages_company_id"), table_name="deal_stages")
    op.drop_table("deal_stages")
    op.drop_index(op.f("ix_clients_company_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_cities_country_id"), table_name="cities")
    op.drop_table("cities")
    op.drop_table("currencies")
    op.drop_table("countries")
    op.drop_table("companies")
    sa.Enum("create", "update", "delete", name="audit_action").drop(op.get_bind())
    sa.Enum("phone", "email", "telegram", "whatsapp", "vk", name="client_contact_type").drop(
        op.get_bind()
    )
    sa.Enum("whatsapp", "telegram", "email", "call", name="message_channel").drop(op.get_bind())
    sa.Enum("in", "out", name="message_direction").drop(op.get_bind())
    sa.Enum("cruise", "tour", "sanatorium", name="funnel_type").drop(op.get_bind())
    sa.Enum(
        "accommodation", "flight", "transfer", "excursion", "other", name="deal_item_type"
    ).drop(op.get_bind())
    sa.Enum("contract", "invoice", "voucher", name="document_type").drop(op.get_bind())
    sa.Enum("draft", "sent", "signed", name="document_status").drop(op.get_bind())
    sa.Enum("image", "document", "audio", "video", "other", name="attachment_file_type").drop(
        op.get_bind()
    )
    sa.Enum("manual", "whatsapp", "telegram", "email", "ocr", name="attachment_source").drop(
        op.get_bind()
    )
    sa.Enum("new", "processing", "converted", "duplicate", "spam", name="lead_status").drop(
        op.get_bind()
    )
    sa.Enum("in", "out", name="payment_direction").drop(op.get_bind())
    sa.Enum("pending", "paid", "failed", "refunded", name="payment_status").drop(op.get_bind())
    sa.Enum("acquiring", "bank_transfer", "cash", "onec_sync", name="payment_method").drop(
        op.get_bind()
    )
    sa.Enum("hotel", "sanatorium", name="accommodation_type").drop(op.get_bind())
    sa.Enum("manual", "nps_parsed", name="accommodation_note_source").drop(op.get_bind())
    sa.Enum("sub_agent", "referral_client", "affiliate", name="partner_type").drop(op.get_bind())
    sa.Enum("open", "in_progress", "done", "overdue", name="task_status").drop(op.get_bind())
    sa.Enum("system", "manual", name="task_created_by").drop(op.get_bind())
    # ### end Alembic commands ###
